# Cloudflare Worker Configuration
name = "beepi-chat-session"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Account ID will be set by Cloudflare during deployment
# For local development, you can uncomment and set it:
# account_id = "your-account-id-here"

# Workers routes (optional - configure based on your domain)
# routes = [
#   { pattern = "example.com/api/chatkit/*", zone_name = "example.com" }
# ]

# Environment variables (non-secret)
# ALLOWED_ORIGINS: Configure which domains can access your API
# Uncomment and set your allowed origins (comma-separated):
[vars]
# ALLOWED_ORIGINS = "https://yourdomain.com,https://www.yourdomain.com"

# Secrets - set these using: wrangler secret put SECRET_NAME
# DO NOT commit actual secret values to version control!
# 
# Required secrets:
# - OPENAI_API_KEY: Your OpenAI API key
# - CHATKIT_WORKFLOW_ID: Your ChatKit workflow ID from Agent Builder
#
# Set secrets with:
#   wrangler secret put OPENAI_API_KEY
#   wrangler secret put CHATKIT_WORKFLOW_ID

# Observability configuration (wrangler v3.88.0+)
[observability]
enabled = false

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

# Placement configuration
[placement]
mode = "smart"
